### ISSUE TITLE
Re: Project to JAVA

### ISSUE THREAD

**Issue by XenXorX** [it-kmitl-2018/group10#15]
แยก front-end กับ back-end

**Comment by champillon** [comment]
ทำให้แล้วครับ

**Comment by amoeba99** [comment]
@champillon พี่ครับรบกวนช่วยล้าง https://github.com/it-kmitl-2018/group10-backend ให้ทีครับ จะเริ่มทำกันใหม่ ขอบคุณครับ

**Comment by champillon** [comment]
ทำ PR มาว่า delete All เลย เมิจเองเลยก็ได้ ไม่ต้องรอพี่
